### ISSUE TITLE
Categories and albums

### ISSUE THREAD

**Issue by aerograf** [mambax7/extgallery#2]
Categories are created, but albums can not be created.

**Comment by mambax7** [comment]
What steps are you using to create the album?

**Comment by aerograf** [comment]
I create in the Catalog & Album.
Then I make a directory with a parent category.
Here and there are problems.
And after creating a category & album in it, you can not upload and post photos.
Permissions I install. True common, tk. there is an error when setting access rights by items.

**Comment by mambax7** [comment]
I hope, this update will fix it. Please let me know...
https://github.com/mambax7/extgallery/commit/069c91e1e55e1125ecc3a18727310324d0e58efd

**Comment by aerograf** [comment]
When upgrading:
Error: Can not use object of type stdClass as array in /modules/extgallery/include/onupdate.php line 202

**Comment by aerograf** [comment]
Now categories are not created.
I'm using an earlier version of the module. There, after creating the category, you can immediately upload a photo to it and this will be an album. If you create a subcategory, it will be already with the category and albums.

**Comment by mambax7** [comment]
Didn't test an upgrade, only installation.  Can you try new installation?

**Comment by aerograf** [comment]
New installation:
Error: Can not use object of type stdClass as array in /modules/extgallery/include/oninstall.php line 184

**Comment by mambax7** [comment]
OK, it should be fixed now. Sorry for the bug!

**Comment by aerograf** [comment]
Checked, working. Thank you.
